# -*- coding: utf-8 -*-
"""math_VMSL_assignment-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bht4s9G02Ux6rAG5_HCxk3A3xIfU7Ie5
"""

n = 5
s_x = 15
x_2 = 15**2     ## (x)2
s_y = 20
s_x2 = 55       ## (x2)
s_y2 = 86
s_xy = 66

a = ((n*s_xy)-(s_x*s_y))

b = (n*s_x2)-x_2

print(a)

print(b)

m = a/b
print(m)

d = (s_y*s_x2)-((s_x)*(s_xy))
print(d)

e = ((n*s_x2)-(x_2))
print(e)

c = d/e

print(c)

X = int(input("Enter independent value : "))

Y = m * X + c

print(Y)

